version: '3.9'
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db


  app:
    container_name: signaling_container
    depends_on:
      - mongodb
    build: .
    command: nodemon server.js 0.0.0.0 8080
    env_file: .env
    ports:
      - 8000:8080
    environment:
      - NODE_PORT=$SERVER_PORT
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    volumes:
      - .:/app
volumes:
  mongo-data: {}